services:

  db:
    image: mysql:8.0
    container_name: bookstore_db
    restart: always
    environment:
      - MYSQL_DATABASE=bookstore
      - MYSQL_ROOT_PASSWORD=secret_password
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  tests:
    build: .
    container_name: python_qa_env
    depends_on:
      - db
    volumes:
      - .:/app
