CREATE TABLE IF NOT EXISTS books (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    created_at TIMESTAMPS DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO books(title, author) VALUES ('The Lean Startup', 'Eric Ries')